default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: db

development:
  <<: *default
  database: chevalspree_development

test:
  <<: *default
  database: chevalspree_test

production:
  <<: *default
  database: chevalspree_production
  username: chevalspree
  password: <%= ENV['CHEVALSPREE_DATABASE_PASSWORD'] %>
