# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f386028acd0dfae9be816bbd1b2e577ef3a725072608f0050d59edcd42a5870d1ae02c5a95d09fc5b6c3d5c6cc96bacf883be98ffb795026ca0f2beb26c87e39

test:
  secret_key_base: 4192536ec9a77278740991aa50a6d696126176353720f33a5b735580507af5513227ca287ffe5a1e959da8825454123549449f8333cf6946dc60819520e123e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
